name: Test de tests (^^) avec Cypress

on:
  push:
    branches: ["main"]

jobs:
  build_and_test:
    name: Build et test avec Cypress
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test

    steps:
      - uses: actions/checkout@v4

      - name: Installer les dépendances
        run: |
          composer install
          npm install

      - name: Environnement
        run: |
          touch .env.dev
          echo DATABASE_URL="mysql://test:test@mariadb:3306/test?charset=utf8mb4" > .env.dev
          cat .env.dev

      - name: Migration
        run: |
          php bin/console d:d:c
          php bin/console make:migration
          php bin/console d:m:m

      - name: Lancer le serveur
        run: |
          php -S 0.0.0.0:8000 -t public/

      - name: Run Cypress
        run: |
          npm run cypress:run
