name: Test de tests (^^) avec Cypress

on:
  push:
    branches: ["main"]

jobs:
  job:
    name: Message lancé (validation du workflow)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lance un message
        run: echo Workflow valide :) !

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Choppe le repo
        uses: actions/checkout@v4
        run: composer i
      - name: Installer les dépendances
        run: npm i
      - name: Run Cypress
        run: npm run cypress:run
