name: Test de tests (^^) avec Cypress

on:
  push:
    branches: ["main"]

jobs:
  build_and_test:
    name: Build et test avec Cypress
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        restart: always
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Installer les dépendances
        run: |
          composer install
          npm install

      - name: Environnement
        run: |
          touch .env.dev
          echo DATABASE_URL="mysql://test:test@0.0.0.0:3306/test?-MariaDB&charset=utf8mb4" >> .env.dev
          cat .env.dev

      - name: On attend maria
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat-openbsd
          until nc -z -v -w30 mariadb 3306; do
            echo "Waiting for MariaDB to be ready..."
            sleep 5
          done

      - name: Logs mariadb
        run: |
          docker logs mariadb

      - name: Migration
        run: |
          php bin/console d:d:c
          php bin/console make:migration
          php bin/console d:m:m

      - name: Lancer le serveur
        run: |
          php -S 0.0.0.0:8000 -t public/

      - name: Run Cypress
        run: |
          npm run cypress:run
