name: Test de tests (^^) avec Cypress

on:
  push:
    branches: ["main"]

jobs:
  job:
    name: Message lancé (validation du workflow)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lance un message
        run: echo Workflow valide :) !
        
  job:
    name: Machine php
    uses: shivammathur/setup-php@v2
    with:
      php-version: '8.2.4'
      extensions: intl, mbstring, sodium, pdo_mysql
      tools: composer
    steps:
      - name: Choppe le repo
        uses: actions/checkout@v4
        run: composer i
      - name: Installer les dépendances
        run: npm i
      - name: Run Cypress
        run: npm run cypress:run