name: Test de tests (^^) avec Cypress

on:
  push:
    branches: ["main"]

jobs:
  build_and_test:
    name: Build et test avec Cypress
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4

      - name: Installer les dépendances
        run: |
          composer install
          npm install

      - name: Environnement
        run: |
          touch .env.dev
          echo DATABASE_URL="ysql://root:@127.0.0.1:3306/test_db?serverVersion=8.0.32&charset=utf8mb4" >> .env.dev
          cat .env.dev

      - name: Set up the database
        run: |
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MySQL to be available..."
            sleep 1
          done
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:update --force --env=test

      - name: Migration
        run: |
          php bin/console d:d:c
          php bin/console make:migration
          php bin/console d:m:m

      - name: Lancer le serveur
        run: |
          php -S 127.0.0.1:8000 -t public/

      - name: Run Cypress
        run: |
          npm run cypress:run
