name: Test de tests (^^) avec Cypress

on:
  push:
    branches: ["main"]

jobs:
  message:
    name: Message lancé (validation du workflow)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lance un message
        run: echo Workflow valide :) !

  build:
    name: Build et test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installer dépendances
        run: |
          composer i
        run: |
          npm i
      - name: Run Cypress
        run: |
          npm run cypress:run
