name: Test de tests (^^) avec Cypress

on:
  push:
    branches: ["main"]

jobs:
  build_and_test:
    name: Build et test avec Cypress
    runs-on: ubuntu-latest

    # Services
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Installer les dépendances
        run: |
          composer install
          npm install

      - name: Environnement
        run: |
          touch .env.dev
          echo DATABASE_URL="mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@127.0.0.1:3306/${{ secrets.DB_NAME }}?charset=utf8mb4" > .env.dev
          cat .env.dev

      - name: Migration
        run: |
          php bin/console d:d:c
          php bin/console make:migration
          php bin/console d:m:m

      - name: Lancer le serveur
        run: |
          php bin/console server:start

      - name: Run Cypress
        run: |
          npm run cypress:run
